class ConveniaError(Exception):
    def __init__(self, message: str, status_code: int | None = None):
        super().__init__(message)
        self.status_code = status_code


class ConveniaAuthError(ConveniaError): ...
class ConveniaForbiddenError(ConveniaError): ...
class ConveniaNotFoundError(ConveniaError): ...
class ConveniaValidationError(ConveniaError): ...
class ConveniaRateLimitError(ConveniaError): ...
class ConveniaServerError(ConveniaError): ...
class ConveniaConnectionError(ConveniaError): ...
